# Generated by Django 6.0.3 on 2026-03-24 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Operador',
                'verbose_name_plural': 'Tipos de Operador',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('legal_name', models.CharField(max_length=200, verbose_name='Razão Social')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('license_number', models.CharField(blank=True, max_length=50, verbose_name='Nº da Licença')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('director_name', models.CharField(blank=True, max_length=200, verbose_name='Director')),
                ('address', models.TextField(blank=True, verbose_name='Endereço')),
                ('logo', models.ImageField(blank=True, upload_to='operators/logos/', verbose_name='Logótipo')),
                ('brand_color', models.CharField(default='#333333', help_text='Código hex, ex: #E30613', max_length=7, verbose_name='Cor da Marca')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('historical_names', models.JSONField(blank=True, default=list, help_text='Nomes anteriores usados nos ficheiros Excel (ex: ["MTN", "Spacetel"])', verbose_name='Nomes Históricos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operators', to='operators.operatortype', verbose_name='Tipo de Operador')),
            ],
            options={
                'verbose_name': 'Operador',
                'verbose_name_plural': 'Operadores',
                'ordering': ['name'],
            },
        ),
    ]
