# Generated by Django 6.0.3 on 2026-03-24 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('order', models.IntegerField(verbose_name='Ordem')),
                ('is_cumulative', models.BooleanField(default=False, help_text='Dados reportados em formato cumulativo (3M/6M/9M/12M)', verbose_name='Cumulativo')),
            ],
            options={
                'verbose_name': 'Categoria de Indicador',
                'verbose_name_plural': 'Categorias de Indicadores',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Código')),
                ('name', models.CharField(max_length=300, verbose_name='Nome')),
                ('unit', models.CharField(choices=[('number', 'Número'), ('minutes', 'Minutos'), ('calls', 'Chamadas'), ('sms', 'Mensagens SMS'), ('mbps', 'MBPS'), ('gb', 'Gigabytes'), ('mb', 'Megabytes'), ('fcfa', 'F CFA'), ('fcfa_millions', 'Milhões F CFA'), ('kbps', 'Kbps'), ('gbps', 'Gbps'), ('persons', 'Pessoas'), ('percentage', 'Percentagem'), ('ms', 'Milissegundos'), ('text', 'Texto')], default='number', max_length=20, verbose_name='Unidade')),
                ('level', models.IntegerField(default=0, verbose_name='Nível hierárquico')),
                ('is_calculated', models.BooleanField(default=False, verbose_name='Calculado automaticamente')),
                ('formula_type', models.CharField(blank=True, choices=[('', 'Sem fórmula'), ('sum_children', 'Soma dos filhos'), ('sum_operators', 'Soma dos operadores'), ('percentage', 'Percentagem'), ('growth_rate', 'Taxa de crescimento'), ('penetration', 'Taxa de penetração'), ('market_share', 'Quota de mercado')], default='', max_length=50, verbose_name='Tipo de fórmula')),
                ('order', models.IntegerField(verbose_name='Ordem')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='indicators.indicator', verbose_name='Indicador pai')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='indicators.indicatorcategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
                'ordering': ['category__order', 'order'],
                'unique_together': {('category', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('quarter', models.IntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')], verbose_name='Trimestre')),
                ('month', models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], verbose_name='Mês')),
                ('start_date', models.DateField(verbose_name='Data início')),
                ('end_date', models.DateField(verbose_name='Data fim')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Bloqueado')),
            ],
            options={
                'verbose_name': 'Período',
                'verbose_name_plural': 'Períodos',
                'ordering': ['-year', '-quarter', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='OperatorTypeIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_applicable', models.BooleanField(default=True, verbose_name='Aplicável')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Obrigatório')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_type_mappings', to='indicators.indicator', verbose_name='Indicador')),
                ('operator_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_mappings', to='operators.operatortype', verbose_name='Tipo de Operador')),
            ],
            options={
                'verbose_name': 'Indicador por Tipo de Operador',
                'verbose_name_plural': 'Indicadores por Tipo de Operador',
                'unique_together': {('operator_type', 'indicator')},
            },
        ),
    ]
