"""
Mapeamento de sheets Excel para categorias de indicadores
e mapeamento de colunas para cada tipo de ficheiro.
"""

SHEET_TO_CATEGORY = {
    'Estações móveis': 'estacoes_moveis',
    'Estações móveis ': 'estacoes_moveis',
    'Estacoes moveis': 'estacoes_moveis',
    'estacoes_moveis': 'estacoes_moveis',
    'Trafego_originado': 'trafego_originado',
    'Tráfego Originado': 'trafego_originado',
    'trafego_originado': 'trafego_originado',
    'Trafego_Terminado': 'trafego_terminado',
    'Tráfego Terminado': 'trafego_terminado',
    'trafego_terminado': 'trafego_terminado',
    'Trafego_Roaming_Internacional': 'trafego_roaming',
    'Tráfego Roaming Internacional': 'trafego_roaming',
    'trafego_roaming': 'trafego_roaming',
    'LBI': 'lbi',
    'lbi': 'lbi',
    'Internet_Fixo': 'internet_fixo',
    'Internet Fixo': 'internet_fixo',
    'internet_fixo': 'internet_fixo',
    'Internet_Trafic': 'internet_trafic',
    'Internet Trafic': 'internet_trafic',
    'internet_trafic': 'internet_trafic',
    'tarifario_voz': 'tarifario_voz',
    'Tarifário de Voz': 'tarifario_voz',
    'tarifario_voz 1': 'tarifario_voz',
    'RECEITAS': 'receitas',
    'Receitas': 'receitas',
    'receitas': 'receitas',
    'Empregos': 'empregos',
    'empregos': 'empregos',
    'Investimento': 'investimento',
    'investimento': 'investimento',
}

OPERATOR_NAME_MAPPING = {
    'MTN': 'TELECEL',
    'mtn': 'TELECEL',
    'Spacetel': 'TELECEL',
    'Spacetel Guiné-Bissau': 'TELECEL',
    'Spacetel Guiné-Bissau SA': 'TELECEL',
    'TELECEL': 'TELECEL',
    'Telecel': 'TELECEL',
    'Orange': 'ORANGE',
    'ORANGE': 'ORANGE',
    'Orange Bissau': 'ORANGE',
    'Orange Bissau SA': 'ORANGE',
    'Starlink': 'STARLINK',
    'STARLINK': 'STARLINK',
}

MONTHLY_COLUMN_LAYOUT = {
    'indicator_code_col': 0,
    'indicator_name_col': 1,
    'unit_col': 2,
    'data_start_col': 3,
    'months_per_quarter': 3,
    'quarters': {
        1: {'start_col': 3, 'months': [1, 2, 3]},
        2: {'start_col': 6, 'months': [4, 5, 6]},
        3: {'start_col': 9, 'months': [7, 8, 9]},
        4: {'start_col': 12, 'months': [10, 11, 12]},
    },
}

CUMULATIVE_COLUMN_LAYOUT = {
    'indicator_code_col': 0,
    'indicator_name_col': 1,
    'unit_col': 2,
    'year_col': 3,
    'periods': {
        '3M': 4,
        '6M': 5,
        '9M': 6,
        '12M': 7,
    },
    'observation_col': 8,
}

CUMULATIVE_CATEGORIES = {'receitas', 'investimento'}


EXCEL_INDICATOR_MAPPINGS = {
    'estacoes_moveis': [
        {'code': '1.1', 'target': '1.1.1'},
        {'code': '1.1.a', 'target': '1.2.1'},
        {'code': '1.2', 'target': '1.1.2'},
        {'code': '1.2.a', 'target': '1.2.2'},
        {'code': '1.3', 'target': '1.1.3'},
        {'code': '2.1.1', 'target': '4.1'},
        {'code': '2.1.4', 'target': '4.2'},
        {'code': '2.1.5.1', 'target': '2.2.1'},
        {'code': '2.1.5.1.1.p', 'target': '2.1.4'},
        {'code': '2.1.5.1.1.q', 'target': '2.1.2'},
        {'code': '2.1.5.2', 'target': '2.2.2'},
        {'code': '2.1.5.2.1.p', 'target': '2.1.4.1'},
        {'code': '2.1.5.2.1.q', 'target': '2.1.2.1'},
        {'code': '3.1', 'target': '4.3'},
        {'code': '3.1.1', 'target': '4.3.1'},
        {'code': '3.1.2', 'target': '4.3.2'},
        {'code': '3.2', 'target': '4.3.3'},
        {'code': '3.3', 'target': '4.3.4'},
        {'code': '3.4', 'target': '4.3.5'},
    ],
    'trafego_originado': [
        {'name_contains': 'chamadas de voz originadas', 'target': '1'},
        {'code': '1.1.1', 'target': '1.1'},
        {'code': '1.1.2', 'target': '1.2'},
        {'code': '1.1.3', 'target': '1.2.3'},
        {'code': '1.1.5', 'target': '1.3'},
        {'code': '1.1.5.1', 'target': '1.3.1'},
        {'code': '1.1.5.3', 'target': '1.3.2'},
        {'code': '1.1.6', 'target': '1.3.4'},
        {'code': '2.1', 'target': '2'},
        {'code': '2.1.1', 'target': '2.1'},
        {'code': '2.1.2', 'target': '2.2'},
        {'code': '2.1.3', 'target': '2.2.3'},
        {'code': '2.1.5', 'target': '2.3'},
        {'code': '2.1.5.1', 'target': '2.3.1'},
        {'code': '2.1.5.3', 'target': '2.3.2'},
        {'code': '2.1.5.4', 'target': '2.3.4'},
        {'code': '3.1', 'target': '3'},
        {'code': '3.1.1', 'target': '3.1'},
        {'code': '3.1.2', 'target': '3.2'},
        {'code': '3.1.3', 'target': '3.3'},
        {'code': '4a', 'target': '4.1'},
        {'code': '4', 'name_contains': 'redes 3g', 'target': '4.2'},
        {'code': '5', 'name_contains': 'redes 4g', 'target': '4.3'},
        {'code': '5.1', 'target': '4.3.2'},
        {'code': '6a', 'target': '4.1.1'},
        {'code': '6', 'name_contains': 'dados 3g', 'target': '4.2.1'},
        {'code': '6.1.1', 'target': '4.5'},
        {'code': '6.1.2', 'target': '4.6'},
        {'code': '7', 'name_contains': 'rede 4g', 'target': '4.3.1'},
        {'code': '7.1', 'target': '4.3.3'},
        {'code': '7.1.1', 'target': '4.7'},
        {'code': '7.1.2', 'target': '4.8'},
    ],
    'trafego_terminado': [
        {'code': '1.1', 'target': '1'},
        {'code': '1.1.1', 'target': '1.1'},
        {'code': '1.1.2', 'target': '1.1.3'},
        {'code': '1.1.4', 'target': '1.2'},
        {'code': '1.1.4.1', 'target': '1.2.1'},
        {'code': '1.1.4.3', 'target': '1.2.2'},
        {'code': '1.1.4.4', 'target': '1.2.4'},
        {'code': '2.1', 'target': '2'},
        {'code': '2.1.1', 'target': '2.1'},
        {'code': '2.1.2', 'target': '2.1.3'},
        {'code': '2.1.3', 'target': '2.2'},
        {'code': '2.1.3.1', 'target': '2.2.1'},
        {'code': '2.1.3.3', 'target': '2.2.2'},
        {'code': '2.1.3.4', 'target': '2.2.4'},
        {'code': '3.1', 'target': '3'},
        {'code': '3.1.1', 'target': '3.1'},
        {'code': '3.1.2', 'target': '3.2'},
    ],
    'trafego_roaming': [
        {'code': '1.1', 'target': '1.1.1'},
        {'code': '1.2', 'target': '1.1.2'},
        {'code': '2.1', 'target': '1.2.1'},
        {'code': '2.2', 'target': '1.2.2'},
        {'code': '3.1', 'target': '1.3.1'},
        {'code': '3.2', 'target': '1.3.2'},
        {'code': '3.3', 'target': '1.4'},
        {'code': '3.4', 'target': '1.4.1'},
        {'code': '4.1', 'target': '2.1.1'},
        {'code': '4.2', 'target': '2.1.2'},
        {'code': '5.1', 'target': '2.2.1'},
        {'code': '5.2', 'target': '2.2.2'},
        {'code': '6.1', 'target': '2.3.1'},
        {'code': '6.2', 'target': '2.4'},
        {'code': '6.3', 'target': '2.4.1'},
        {'code': '7.1', 'target': '2.5'},
    ],
    'lbi': [
        {'code': '1.2.1', 'target': '1'},
        {'code': '1.2.1.1.1', 'target': '1.1.1'},
        {'code': '1.2.1.1.1.1', 'target': '1.2'},
        {'code': '1.3.1.1.1.1', 'target': '1.3.1'},
        {'name_contains': 'satelite', 'target': '1.3'},
        {'name_contains': 'fibra optica', 'target': '1.4'},
        {'name_contains': 'feixe hertziano', 'target': '1.5'},
    ],
    'internet_fixo': [
        {'code': '1', 'target': '1'},
        {'code': '1.1', 'target': '1.1'},
        {'code': '1.2', 'target': '1.2'},
        {'code': '1.3', 'target': '1.6'},
        {'code': '2.2.1', 'target': '2.2'},
        {'code': '2.2.2', 'target': '2.3'},
        {'code': '2.2.3', 'target': '2.4'},
        {'code': '2.2.4', 'target': '2.5'},
        {'code': '3.1', 'target': '3.1'},
        {'code': '3.2', 'target': '3.2'},
        {'code': '3.3', 'target': '3.3'},
        {'code': '3.3.1', 'target': '3.5'},
        {'code': '3.3.2', 'target': '3.3.1'},
        {'code': '4', 'name_contains': 'ong', 'target': '3.6'},
        {'code': '5.1', 'target': '4.1'},
        {'code': '5.2', 'target': '4.5'},
        {'code': '5.3', 'target': '4.2'},
        {'code': '5.4', 'target': '4.9'},
        {'code': '5.5', 'target': '4.3'},
        {'code': '5.6', 'target': '4.6'},
        {'code': '5.7', 'target': '4.4'},
        {'code': '5.8', 'target': '4.8'},
        {'code': '5.9', 'target': '4.7'},
    ],
    'internet_trafic': [
        {'code': '2.2', 'name_contains': 'banda larga', 'target': '1'},
    ],
    'receitas': [
        {'code': '1', 'name_contains': 'receitas totais do servico', 'target': '8'},
        {'code': '1.1.2', 'name_contains': 'receitas de servicos de voz', 'target': '1'},
        {'code': '1.1.2.1', 'target': '1.1'},
        {'code': '1.1.2.2', 'target': '1.2'},
        {'code': '1.1.2.4', 'target': '1.3'},
        {'code': '1.1.3', 'target': '1.4'},
        {'code': '1.1.4', 'target': '3'},
        {'code': '1.1.5', 'target': '4.1'},
        {'code': '1.2.1', 'name_contains': 'terminacao de voz', 'target': '2'},
        {'code': '1.2.1.1', 'target': '2.1'},
        {'code': '1.2.1.3', 'target': '2.2'},
        {'code': '1', 'name_contains': 'internet fixo via radio', 'target': '4.2'},
    ],
    'empregos': [
        {'code': '1.1', 'target': '1'},
        {'code': '1.1.1', 'target': '1.1'},
        {'code': '1.1.1.1', 'target': '1.1.1'},
        {'code': '1.1.1.2', 'target': '1.1.2'},
        {'code': '1.2', 'target': '2'},
    ],
    'investimento': [
        {'name_contains': 'total geral', 'target': '1'},
        {'code': '1.1', 'name_contains': 'servicos de telecomunicacoes', 'target': '1.1'},
        {'code': '1.1', 'name_contains': 'torres', 'target': '1.1.1.1'},
        {'code': '1.1', 'name_contains': 'paineis solares', 'target': '1.1.1.1'},
        {'code': '1.1', 'name_contains': 'batarias', 'target': '1.1.1.1'},
        {'code': '1.1', 'name_contains': 'estruturas metalicas', 'target': '1.1.1.1'},
        {'code': '1.1', 'name_contains': 'radios', 'target': '1.1.1.1'},
        {'code': '1.1', 'name_contains': 'geradores', 'target': '1.1.1.1'},
        {'code': '1.1', 'name_contains': 'informaticos', 'target': '1.1.1.2'},
        {'code': '1.1', 'name_contains': 'carros', 'target': '1.1.1.5'},
        {'code': '1.2', 'name_contains': 'servicos de internet', 'target': '1.2'},
        {'code': '2.1', 'name_contains': 'licencas', 'target': '1.1.2.1'},
    ],
}
