# Generated by Django 6.0.3 on 2026-03-24 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicators', '0001_initial'),
        ('operators', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataValidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('min_value', 'Valor Mínimo'), ('max_value', 'Valor Máximo'), ('not_null', 'Não pode ser nulo'), ('growth_limit', 'Limite de crescimento (%)'), ('consistency', 'Consistência com outros indicadores')], max_length=30, verbose_name='Tipo de regra')),
                ('value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Valor')),
                ('error_message', models.CharField(max_length=500, verbose_name='Mensagem de erro')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_rules', to='indicators.indicator', verbose_name='Indicador')),
                ('related_indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_rules', to='indicators.indicator', verbose_name='Indicador relacionado')),
            ],
            options={
                'verbose_name': 'Regra de Validação',
                'verbose_name_plural': 'Regras de Validação',
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/', verbose_name='Ficheiro')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nome do ficheiro')),
                ('file_type', models.CharField(choices=[('questionnaire_telecel', 'Questionário Telecel'), ('questionnaire_orange', 'Questionário Orange'), ('questionnaire_starlink', 'Questionário Starlink'), ('kpi_orange', 'KPI Orange'), ('statistics', 'Dados Estatísticos Consolidados'), ('other', 'Outro')], default='other', max_length=30, verbose_name='Tipo')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('quarter', models.IntegerField(blank=True, null=True, verbose_name='Trimestre')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Em Processamento'), ('processed', 'Processado'), ('error', 'Erro'), ('validated', 'Validado')], default='uploaded', max_length=20, verbose_name='Estado')),
                ('processing_log', models.TextField(blank=True, verbose_name='Log de processamento')),
                ('records_imported', models.IntegerField(default=0, verbose_name='Registos importados')),
                ('records_errors', models.IntegerField(default=0, verbose_name='Erros')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de upload')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de processamento')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='operators.operator', verbose_name='Operador')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Carregado por')),
            ],
            options={
                'verbose_name': 'Upload de Ficheiro',
                'verbose_name_plural': 'Uploads de Ficheiros',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CumulativeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('cumulative_type', models.CharField(choices=[('3M', '3 Meses (Jan-Mar)'), ('6M', '6 Meses (Jan-Jun)'), ('9M', '9 Meses (Jan-Set)'), ('12M', '12 Meses (Jan-Dez)')], max_length=5, verbose_name='Período cumulativo')),
                ('value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Valor')),
                ('observation', models.TextField(blank=True, verbose_name='Observação')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de submissão')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('manual', 'Entrada Manual'), ('upload', 'Upload Excel'), ('calculated', 'Calculado Automaticamente'), ('imported', 'Importado')], default='manual', max_length=20, verbose_name='Fonte')),
                ('is_validated', models.BooleanField(default=False, verbose_name='Validado')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cumulative_entries', to='indicators.indicator', verbose_name='Indicador')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cumulative_entries', to='operators.operator', verbose_name='Operador')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Submetido por')),
            ],
            options={
                'verbose_name': 'Dados Cumulativos',
                'verbose_name_plural': 'Dados Cumulativos',
                'unique_together': {('indicator', 'operator', 'year', 'cumulative_type')},
            },
        ),
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Valor')),
                ('observation', models.TextField(blank=True, verbose_name='Observação')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de submissão')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualização')),
                ('source', models.CharField(choices=[('manual', 'Entrada Manual'), ('upload', 'Upload Excel'), ('calculated', 'Calculado Automaticamente'), ('imported', 'Importado')], default='manual', max_length=20, verbose_name='Fonte')),
                ('is_validated', models.BooleanField(default=False, verbose_name='Validado')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de validação')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='indicators.indicator', verbose_name='Indicador')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_entries', to='operators.operator', verbose_name='Operador')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='indicators.period', verbose_name='Período')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Submetido por')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_entries', to=settings.AUTH_USER_MODEL, verbose_name='Validado por')),
            ],
            options={
                'verbose_name': 'Entrada de Dados',
                'verbose_name_plural': 'Entradas de Dados',
                'indexes': [models.Index(fields=['operator', 'period'], name='data_entry__operato_ec2020_idx'), models.Index(fields=['indicator', 'period'], name='data_entry__indicat_f1a7c9_idx'), models.Index(fields=['operator', 'indicator'], name='data_entry__operato_5ee9b6_idx')],
                'unique_together': {('indicator', 'operator', 'period')},
            },
        ),
    ]
