# Generated by Django 4.2.7 on 2026-03-25 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operators', '0001_initial'),
        ('indicators', '0001_initial'),
        ('data_entry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDataEntry',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Valor')),
                ('observation', models.TextField(blank=True, verbose_name='Observação')),
                ('submitted_at', models.DateTimeField(blank=True, editable=False, verbose_name='Data de submissão')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Última actualização')),
                ('source', models.CharField(choices=[('manual', 'Entrada Manual'), ('upload', 'Upload Excel'), ('calculated', 'Calculado Automaticamente'), ('imported', 'Importado')], default='manual', max_length=20, verbose_name='Fonte')),
                ('is_validated', models.BooleanField(default=False, verbose_name='Validado')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de validação')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('indicator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indicators.indicator', verbose_name='Indicador')),
                ('operator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operators.operator', verbose_name='Operador')),
                ('period', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indicators.period', verbose_name='Período')),
                ('submitted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Submetido por')),
                ('validated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Validado por')),
            ],
            options={
                'verbose_name': 'historical Entrada de Dados',
                'verbose_name_plural': 'historical Entradas de Dados',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCumulativeData',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('cumulative_type', models.CharField(choices=[('3M', '3 Meses (Jan-Mar)'), ('6M', '6 Meses (Jan-Jun)'), ('9M', '9 Meses (Jan-Set)'), ('12M', '12 Meses (Jan-Dez)')], max_length=5, verbose_name='Período cumulativo')),
                ('value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Valor')),
                ('observation', models.TextField(blank=True, verbose_name='Observação')),
                ('submitted_at', models.DateTimeField(blank=True, editable=False, verbose_name='Data de submissão')),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('source', models.CharField(choices=[('manual', 'Entrada Manual'), ('upload', 'Upload Excel'), ('calculated', 'Calculado Automaticamente'), ('imported', 'Importado')], default='manual', max_length=20, verbose_name='Fonte')),
                ('is_validated', models.BooleanField(default=False, verbose_name='Validado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('indicator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indicators.indicator', verbose_name='Indicador')),
                ('operator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operators.operator', verbose_name='Operador')),
                ('submitted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Submetido por')),
            ],
            options={
                'verbose_name': 'historical Dados Cumulativos',
                'verbose_name_plural': 'historical Dados Cumulativos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
