# Generated by Django 6.0.3 on 2026-05-12 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0002_historicaldataentry_historicalcumulativedata'),
        ('operators', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='received_documents/%Y/%m/', verbose_name='Ficheiro')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nome original')),
                ('document_type', models.CharField(choices=[('questionnaire', 'Questionário preenchido'), ('kpi_summary', 'Resumo KPI'), ('supporting_document', 'Documento de suporte'), ('correspondence', 'Correspondência'), ('other', 'Outro')], default='questionnaire', max_length=30, verbose_name='Tipo de documento')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('quarter', models.IntegerField(blank=True, null=True, verbose_name='Trimestre')),
                ('status', models.CharField(choices=[('received', 'Recebido'), ('classifying', 'Em classificação'), ('extracting', 'Em extracção'), ('reviewing', 'Em revisão'), ('validated', 'Validado'), ('imported', 'Importado'), ('archived', 'Arquivado')], default='received', max_length=20, verbose_name='Estado')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('normal', 'Normal'), ('high', 'Alta')], default='normal', max_length=10, verbose_name='Prioridade')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Prazo interno')),
                ('notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('checklist', models.JSONField(blank=True, default=dict, verbose_name='Checklist')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de registo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualização')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_documents', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_documents', to='operators.operator', verbose_name='Operador')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_documents', to=settings.AUTH_USER_MODEL, verbose_name='Recebido por')),
            ],
            options={
                'verbose_name': 'Documento Recebido',
                'verbose_name_plural': 'Documentos Recebidos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['operator', 'year'], name='data_entry__operato_c0b67b_idx'), models.Index(fields=['status', 'priority'], name='data_entry__status_810b10_idx'), models.Index(fields=['assigned_to', 'status'], name='data_entry__assigne_c79ed8_idx')],
            },
        ),
    ]
