# Generated by Django 6.0.3 on 2026-05-12 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0003_receiveddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='received_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to='data_entry.receiveddocument', verbose_name='Documento recebido'),
        ),
    ]
