# Generated by Django 6.0.3 on 2026-03-24 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('report_type', models.CharField(max_length=20, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('sections', models.JSONField(default=list, verbose_name='Secções')),
                ('is_default', models.BooleanField(default=False, verbose_name='Padrão')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Template de Relatório',
                'verbose_name_plural': 'Templates de Relatório',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('report_type', models.CharField(choices=[('quarterly', 'Relatório Trimestral'), ('annual', 'Relatório Anual'), ('custom', 'Relatório Personalizado')], max_length=20, verbose_name='Tipo')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('quarter', models.IntegerField(blank=True, null=True, verbose_name='Trimestre')),
                ('pdf_file', models.FileField(blank=True, upload_to='reports/pdf/%Y/', verbose_name='Ficheiro PDF')),
                ('excel_file', models.FileField(blank=True, upload_to='reports/excel/%Y/', verbose_name='Ficheiro Excel')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de geração')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('generating', 'Em Geração'), ('ready', 'Pronto'), ('published', 'Publicado'), ('error', 'Erro')], default='draft', max_length=20, verbose_name='Estado')),
                ('executive_summary', models.TextField(blank=True, verbose_name='Resumo executivo')),
                ('sections', models.JSONField(blank=True, default=dict, verbose_name='Secções')),
                ('error_log', models.TextField(blank=True, verbose_name='Log de erros')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Gerado por')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'ordering': ['-generated_at'],
            },
        ),
    ]
